#!/bin/bash

touch count
x=$(cat count)
let "x += 1"
echo -n "$x" > count

if test "$x" -gt 10; then
    rm -f unhappy
else
    echo "$x"
    y=$(($x+6))
    z=$(($x+20))
    ./randsleep $y $z
    touch unhappy
fi

exit 0


